export const ROLE_SYSTEM_ADMIN = 'SYSTEM_ADMIN'
export const ROLE_CLIENT = 'CLIENT'
export const ROLE_MANAGER = 'MANAGER'
export const ROLE_ADMINISTRATOR = 'ADMINISTRATOR'

export const USER_ROLES = [
    ROLE_SYSTEM_ADMIN,
    ROLE_CLIENT,
    ROLE_MANAGER,
    ROLE_ADMINISTRATOR
]
